--liquibase formatted sql

--changeset skulazhanka:1
CREATE TABLE IF NOT EXISTS City
(
    id   INT primary key generated by default as identity,
    name VARCHAR not null
);

--changeset skulazhanka:2
CREATE TABLE IF NOT EXISTS Route
(
    id               INT primary key generated by default as identity,
    departure_city   VARCHAR,
    destination_city VARCHAR
);

--changeset skulazhanka:3
CREATE TABLE IF NOT EXISTS Client
(
    id           INT primary key generated by default as identity,
    name         VARCHAR not null,
    surname      VARCHAR not null,
    mobile_phone INT     not null,
    e_mail       INT     not null unique
);

--changeset skulazhanka:4
CREATE TABLE IF NOT EXISTS Booking
(
    id        INT primary key generated by default as identity,
    client_id int REFERENCES client (id),
    status    VARCHAR,
    date      TIMESTAMP,
    departure_city   VARCHAR,
    destination_city VARCHAR,
    number_people INTEGER
)
