--liquibase formatted sql

--changeset skulazhanka:1
CREATE TABLE IF NOT EXISTS Station
(
    id INT primary key generated by default as identity,
    city_id INT REFERENCES city (id),
    station VARCHAR
    );

INSERT INTO Station (id, city_id,station)
VALUES (1, 1, 'Central bus station'),
       (2, 1, 'Vostok'),
       (3, 2, 'Central bu station'),
       (4, 3, 'ZIP'),
       (5, 3, 'Selmash'),
       (6, 3, '8 March'),
       (7, 3, 'Solnechnaja'),
       (8, 3, 'Mandarin'),
       (9, 3, 'Сircus'),
       (10, 3, 'Central bus station');



