--liquibase formatted sql

--changeset skulazhanka:1
CREATE TABLE IF NOT EXISTS City
(
    id   INT primary key generated by default as identity,
    name VARCHAR not null
);

--changeset skulazhanka:2
insert into City (name) values
                            ('Minks'),
                            ('Brest'),
                            ('Homel'),
                            ('Vitebsk'),
                            ('Grodo'),
                            ('Mogilev');

--changeset skulazhanka:3
CREATE TABLE IF NOT EXISTS Route
(
    id               INT primary key generated by default as identity,
    departure_city   VARCHAR,
    destination_city VARCHAR
);

--changeset skulazhanka:4
INSERT INTO Route (id, departure_city, destination_city)
VALUES (1, 'Minsk', 'Grodno'),
       (2, 'Minsk', 'Gomel'),
       (3, 'Minsk', 'Vitebsk'),
       (4, 'Grodno', 'Minsk'),
       (5, 'Gomel', 'Minsk');


--changeset skulazhanka:5
CREATE TABLE IF NOT EXISTS Client
(
    id           INT primary key generated by default as identity,
    name         VARCHAR not null,
    surname      VARCHAR not null,
    mobile_phone INT     not null,
    e_mail       VARCHAR     not null unique
);


--changeset skulazhanka:6
insert into client (name , surname, mobile_phone,e_mail ) values
    ('Jon','Doe', 45564, 'JonDoe@gmail.com');

--changeset skulazhanka:7
CREATE TABLE IF NOT EXISTS Booking
(
    id        INT primary key generated by default as identity,
    client_id int REFERENCES client (id),
    status    VARCHAR,
    date      TIMESTAMP,
    departure_city   VARCHAR,
    destination_city VARCHAR,
    number_people INTEGER
)
