--liquibase formatted sql

--changeset skulazhanka:1
CREATE TABLE IF NOT EXISTS Station
(
    id INT primary key generated by default as identity,
    city_id INT REFERENCES city (id),
    station VARCHAR
    );

INSERT INTO Station (id, city_id,station)
VALUES (1, 1, 'Central bus station'),
       (2, 1, 'Vostok'),
       (3, 1, 'St.M. Moscow'),
       (4, 3, 'Central bus station'),
       (5, 3, 'ZIP'),
       (6, 2, 'Central bu station'),
       (7, 2, 'Tower');



