--liquibase formatted sql

--changeset skulazhanka:1
CREATE TABLE IF NOT EXISTS Schedule
(
    id               INT primary key generated by default as identity,
    route_id         INT REFERENCES Route (id),
    date             DATE,
    time             TIME,
    amount_passengers INT
    );

INSERT INTO route (id, departure_city, destination_city)
VALUES (1, 'Minsk', 'Grodno'),
       (2, 'Minsk', 'Gomel'),
       (3, 'Minsk', 'Vitebsk'),
       (4, 'Grodno', 'Minsk'),
       (5, 'Gomel', 'Minsk');


INSERT INTO schedule (id, route_id, date, time, amount_passengers)
VALUES (1, 1, '2023-08-10', '13:30:00', 3),
 (2, 1, '2023-08-10', '14:30:00', 1),
 (3, 1, '2023-08-10', '15:30:00', 1),
 (4, 5, '2023-08-10', '10:30:00', 1),
 (5, 5, '2023-08-10', '12:30:00', 1);


