--liquibase formatted sql

--changeset skulazhanka:1
CREATE TABLE IF NOT EXISTS Schedule
(
    id               INT primary key generated by default as identity,
    route_id         INT REFERENCES Route (id),
    date             DATE,
    time             TIME,
    amount_passengers INT
    );

INSERT INTO Schedule (id, route_id, date, time, amount_passengers)
VALUES
(1, 1, '2023-01-01', '13:30:00', 3),
(2, 1, '2023-01-01', '14:30:00', 1),
(3, 1, '2023-01-01', '15:30:00', 1),
(4, 5, '2023-01-01', '10:30:00', 1),
(5, 5, '2023-01-01', '12:30:00', 1),
(6, 1, '2023-02-01', '13:30:00', 13),
(7, 5, '2023-02-01', '12:30:00', 15);
